# Generated by Django 2.2 on 2019-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='photo',
            field=models.ImageField(default='logo.png', upload_to='photos'),
        ),
    ]
